# Generated by Django 5.1 on 2024-08-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fakemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('image', models.ImageField(upload_to='fakemon_images/')),
                ('type1', models.CharField(choices=[('Normal', 'Normal'), ('Fire', 'Fire'), ('Water', 'Water'), ('Electric', 'Electric'), ('Grass', 'Grass'), ('Ice', 'Ice'), ('Fighting', 'Fighting'), ('Poison', 'Poison'), ('Ground', 'Ground'), ('Flying', 'Flying'), ('Psychic', 'Psychic'), ('Bug', 'Bug'), ('Rock', 'Rock'), ('Ghost', 'Ghost'), ('Dragon', 'Dragon'), ('Dark', 'Dark'), ('Steel', 'Steel'), ('Fairy', 'Fairy')], max_length=100)),
                ('type2', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Fire', 'Fire'), ('Water', 'Water'), ('Electric', 'Electric'), ('Grass', 'Grass'), ('Ice', 'Ice'), ('Fighting', 'Fighting'), ('Poison', 'Poison'), ('Ground', 'Ground'), ('Flying', 'Flying'), ('Psychic', 'Psychic'), ('Bug', 'Bug'), ('Rock', 'Rock'), ('Ghost', 'Ghost'), ('Dragon', 'Dragon'), ('Dark', 'Dark'), ('Steel', 'Steel'), ('Fairy', 'Fairy')], max_length=100)),
            ],
        ),
    ]
