# Generated by Django 5.1 on 2024-08-21 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fakemon', '0002_alter_fakemon_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fakemon',
            name='height',
        ),
        migrations.RemoveField(
            model_name='fakemon',
            name='weight',
        ),
    ]
